### ISSUE TITLE
Spam on the home page

### ISSUE THREAD

**Issue by redblobgames** [walnut-io/walnut-io#1]
I know, Walnut is no longer active, but someone has modified your home page to include a link to "buyinstagramlikes". :-(

**Comment by ryanfaerman** [comment]
I’ve double checked, but there are no links like that in any source or rendered website. What url are you referring to? Have you checked your own browser?

**Comment by redblobgames** [comment]
Oh, oops, I'm terribly sorry. I was looking at the wrong site, which is *also* called Walnut, but is not actually walnut.io but under a different domain. My apologies.
